# -*- coding: utf-8 -*-
"""MidtermExam_OOP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110FT5NbSFG1Mx9-viFuUUZWewow59-av
"""

def main():
 class TemperatureConversion:
  def __init__(self, temp=1):
   self._temp = temp
 class CelsiusToFahrenheit(TemperatureConversion):
  def conversion(self):
   return (self._temp * 9) / 5 + 32
 class CelsiusToKelvin(TemperatureConversion):
  def conversion(self):
   return self._temp + 273.15
 class FahrenheitToCelsius(TemperatureConversion):
  def conversion(self):
    return (self._temp - 32) / 1.8
 class KelvinToCelsius(TemperatureConversion):
        def conversion(self):
            return self._temp - 273.15

 tempInCelsius = float(input("Enter the temperature in Celsius: "))
 convert = CelsiusToKelvin(tempInCelsius)
 print(str(convert.conversion()) + " Kelvin")
 convert = CelsiusToFahrenheit(tempInCelsius)
 print(str(convert.conversion()) + " Fahrenheit")
 convert = FahrenheitToCelsius(tempInCelsius)
 print(str(convert.conversion()) + " Celsius")
 convert = KelvinToCelsius(tempInCelsius)
 print(str(convert.conversion()) + " Celsius")



main()

import sys
from PyQt6.QtWidgets import QWidget, QApplication, QPushButton
from PyQt6.QtGui import QIcon

class App(QWidget):

    def __init__(self):
        super().__init__()
        self.title = "PyQt Button"
        self.x = 200
        self.y = 200
        self.width = 300
        self.height = 300
        self.initUI()

    def initUI(self):
        self.setWindowTitle(self.title)
        self.setGeometry(self.x, self.y, self.width, self.height)
        self.setWindowIcon(QIcon('pythonico.ico'))

        # First Button
        self.btn_click = QPushButton('Click me!', self)
        self.btn_click.setToolTip("You've hovered over me!")
        self.btn_click.move(100, 70)

        # Second Button (Styled Yellow)
        self.btn_register = QPushButton('Register', self)
        self.btn_register.setToolTip("This button does nothing.. yet..")
        self.btn_register.move(100, 100)

        # --- Change button background color to yellow ---
        self.btn_register.setStyleSheet("background-color: yellow;")

        self.show()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = App()
    sys.exit(app.exec())

import sys
from PyQt6.QtGui import QIcon
from PyQt6.QtWidgets import QApplication, QLabel, QLineEdit, QPushButton, QWidget


class App(QWidget):

    def __init__(self):
        super().__init__()
        self.title = "Midterm in OOP"
        self.x = 200
        self.y = 200
        self.width = 500
        self.height = 300
        self.initUI()

    def initUI(self):
        self.setWindowTitle(self.title)
        self.setGeometry(self.x, self.y, self.width, self.height)
        self.setWindowIcon(QIcon("pythonico.ico"))

        # Label for input field
        self.label_input = QLabel("Enter your fullname:", self)
        self.label_input.move(50, 80)
        self.label_input.resize(200, 30)

        # Input text field
        self.textbox_input = QLineEdit(self)
        self.textbox_input.move(220, 80)
        self.textbox_input.resize(200, 30)

        # Button to trigger display
        self.btn = QPushButton("Click to display your Fullname", self)
        self.btn.move(50, 130)
        self.btn.resize(160, 30)
        self.btn.clicked.connect(self.display_fullname)

        # Output text field
        self.textbox_output = QLineEdit(self)
        self.textbox_output.move(220, 130)
        self.textbox_output.resize(200, 30)
        self.textbox_output.setReadOnly(
            True
        )  # Set to read-only so it displays output

        self.show()

    def display_fullname(self):
        # Get text from input textbox and set it in output textbox
        user_input = self.textbox_input.text()
        self.textbox_output.setText(user_input)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ex = App()
    sys.exit(app.exec())